LOAD DATA INFILE `./MYSQLData/ISA-Tab.csv` 
INTO TABLE `ISA-Tab`
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE './MYSQLData/Study.csv'
INTO TABLE Study
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE './MYSQLData/Protocol.csv'
INTO TABLE Protocol
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE './MYSQLData/Keyword.csv' 
INTO TABLE `Keyword`
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE './MYSQLData/has_tag.csv' 
INTO TABLE `ISA-Tab`
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE './MYSQLData/Tag.csv' 
INTO TABLE `ISA-Tab`
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';